# Generated by Django 5.0.6 on 2024-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news_post',
            name='short_description',
            field=models.CharField(max_length=250, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название новости'),
        ),
    ]
